#ifndef __AES_Basic__
#define __AES_Basic__

//#define __Aes__Increment_Counter_BE

#define AES_WORD_SIZE (32 / 8)
#define AES_DWORD_SIZE (64 / 8)
#define AES_128V_SIZE (128 / 8)

#define ROUNDS 14

#define KEY_SIZE 32
#define KEY_SIZEW (KEY_SIZE / AES_WORD_SIZE)
#define KEY_SIZEDW (KEY_SIZE / AES_DWORD_SIZE)

#define BLOCK_SIZE 16
#define BLOCK_SIZEW (BLOCK_SIZE / AES_WORD_SIZE)
#define BLOCK_SIZEDW (BLOCK_SIZE / AES_DWORD_SIZE)
#define BLOCK_SIZE_SHIFT 4

#define EKEY_SIZE ((ROUNDS + 1) * BLOCK_SIZE)
#define EKEY_SIZEW (EKEY_SIZE / AES_WORD_SIZE)

#define CTR_SIZE BLOCK_SIZE
#define CTR_SIZEW (CTR_SIZE / AES_WORD_SIZE)
#define CTR_SIZEV128 (CTR_SIZE / AES_128V_SIZE)

#define AES_HANDLE_SIZE (CTR_SIZE + EKEY_SIZE)
#define AES_HANDLE_SIZEW (AES_HANDLE_SIZE / AES_WORD_SIZE)
#define AES_HANDLE_ALIGN 16

#define AES_HANDLE_CTR_START 0
#define AES_HANDLE_CTR_STARTW (AES_HANDLE_CTR_START / AES_WORD_SIZE)
#define AES_HANDLE_CTR_STARTDW (AES_HANDLE_CTR_START / AES_DWORD_SIZE)
#define AES_HANDLE_CTR_STARTV128 (AES_HANDLE_CTR_START / AES_128V_SIZE)

#define AES_HANDLE_EKEY_START CTR_SIZE
#define AES_HANDLE_EKEY_STARTW (AES_HANDLE_EKEY_START / AES_WORD_SIZE)
#define AES_HANDLE_EKEY_STARTV128 (AES_HANDLE_EKEY_START / AES_128V_SIZE)

#endif //__AES_Basic__